[CI][PR Title] Allow multiple categories in PR title  (#822)
This PR updates the workflow to check the PR title and allow multiple
categories:
```
[Category1][Category2]...[CategoryN] Description sentence
```

(cherry picked from commit 849603ecb38a11f1b49fbaeb6ee712b137746eb1)

diff --git a/.github/workflows/check-pr-title.yaml b/.github/workflows/check-pr-title.yaml
--- a/.github/workflows/check-pr-title.yaml
+++ b/.github/workflows/check-pr-title.yaml
@@ -19,9 +19,15 @@ jobs:
           MAX_TITLE_LENGTH=72
           PR_TITLE='${{ github.event.pull_request.title }}'
 
-          # Ensure the title matches the format [Category] Title
-          if [[ ! "$PR_TITLE" =~ ^\[[^\]]+\]\ .+ ]]; then
-            echo "::error::PR title must be in the format '[Category] Title'."
+          # Ensure the title matches the format [Category1][Category2]...[CategoryN] A sentence
+          if [[ ! "$PR_TITLE" =~ ^(\[[^\]]+\])+ ]]; then
+            echo "::error::PR title must be in the format '[Category1][Category2]...[CategoryN] A sentence'."
+            exit 1
+          fi
+
+          # Ensure there is a space after the last category
+          if [[ ! "$PR_TITLE" =~ ^(\[[^\]]+\])+\ .+ ]]; then
+            echo "::error::PR title must contain a space after the last category."
             exit 1
           fi
 
